[package]
name = "php-literal-parser"
description = "parser for php literals"
version = "0.1.1"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/icewind1991/php-literal-parser"
documentation = "https://docs.rs/php-literal-parser"

[dependencies]
logos = "0.11"
thiserror = "1.0"
source-span = "2.2"

[dev-dependencies]
maplit = "1.0.2"