[package]
name = "php-literal-parser"
description = "parser for php literals"
version = "0.4.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/icewind1991/php-literal-parser"
documentation = "https://docs.rs/php-literal-parser"

[dependencies]
logos = "0.12"
thiserror = "1"
memchr = "2"
serde = "1"
miette = "3"

[dev-dependencies]
maplit = "1"
serde_derive = "1"
miette = { version = "3", features = ["fancy"] }