[package]
name = "php-literal-parser"
description = "parser for php literals"
version = "0.2.9"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/icewind1991/php-literal-parser"
documentation = "https://docs.rs/php-literal-parser"

[dependencies]
logos = "0.12"
thiserror = "1.0"
source-span = { version = "=2.2.1", default-features = false }
memchr = "2.3.4"
serde = "1.0"

[dev-dependencies]
maplit = "1.0.2"
serde_derive = "1.0"

[features]
default = ["colors"]
colors = ["source-span/colors"]